### PR TITLE
Nullity propagation

### PR DESCRIPTION
**Pull request by ilya-klyuchnikov**

### CODE REVIEW

**Comment by ilya-klyuchnikov** [comment]
This change, unfortunately, removes some contracts.

Example:

``` java
@Contract("null->null")
int[] id(int[] v) {
  return v;
}

// this contract is not inferred anymore
@Contract("null->null")
int[] id1(int[] v) {
  int[] v1 = id(v);
  if (v1 == null) {
    return v1;
  } else {
    return v1;
  }
}
```

when propagating `v1 == null` we loose information that v1 is `id(null)`.

**Comment by controlflow** [comment]
:(

**Comment by ilya-klyuchnikov** [comment]
@controlflow the number of such lost annotations is miserable comparing to new annotations.

**Comment by ilya-klyuchnikov** [comment]
#30 is much more better. This approach is rejected.

**Pull request closed without merging**
